apply plugin: 'com.android.application'

android {
    namespace 'br.com.pilovieira.tk303g'
    compileSdk 34
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    defaultConfig {
        applicationId "br.com.pilovieira.tk303g"
        minSdkVersion 19
        targetSdk 34
        versionCode 13
        versionName "4.0.1"
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
        vectorDrawables.useSupportLibrary = true
        multiDexEnabled true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            applicationIdSuffix ".developer"
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')

//    implementation 'androidx.browser:browser:1.2.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
//    implementation 'androidx.mediarouter:mediarouter:1.1.0'
    implementation 'androidx.multidex:multidex:2.0.1'

    implementation 'com.google.android.gms:play-services-ads:22.6.0'

    implementation 'com.google.android.material:material:1.11.0'

    implementation 'com.j256.ormlite:ormlite-android:4.45'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}