apply plugin: 'com.android.application'

android {
    namespace = 'br.com.pilovieira.tk303g'
    compileSdk = 37
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    defaultConfig {
        applicationId = "br.com.pilovieira.tk303g"
        minSdk = 21
        targetSdk = 37
        versionCode = 14
        versionName = "4.1.0"
        vectorDrawables.useSupportLibrary = true
        multiDexEnabled = true
    }

    buildFeatures {
        buildConfig = true
    }

    buildTypes {
        release {
            minifyEnabled = false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            applicationIdSuffix ".developer"
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')

    implementation 'androidx.appcompat:appcompat:1.8.0'

    implementation 'com.google.android.gms:play-services-ads:25.4.0'

    implementation 'com.google.android.material:material:1.14.0'

    implementation 'com.j256.ormlite:ormlite-android:6.1'
}
